### ISSUE TITLE
Add back TestSetExtensions

### ISSUE THREAD

**Issue by iamed2** [invenia/Memento.jl#102]
when it's ready for 1.0

**Comment by nicoleepp** [comment]
Is there any plan for https://github.com/ssfrr/TestSetExtensions.jl to be updated for 1.0? There hasn't been any dev on it in over a year

**Comment by ararslan** [comment]
Last I heard, there were changes to the Test stdlib that make it so that TestSetExtensions can no longer work on 1.0. I can't point to a particular discussion though, as they may have been had on Slack, and quite a while ago.

**Comment by nicoleepp** [comment]
Closing for now. Can be re-opened if TestSetExtensions gets revived.
