### ISSUE TITLE
Using separate levels on different handlers

### ISSUE THREAD

**Issue by lwabeke** [invenia/Memento.jl#11]
Hi

I'm guessing it is possible, but I'm probably just misunderstanding it from the docs.
I would like to setup 2 handlers:
-A File logger to log from debug upwards
-Stdout console logger to only log from warning upwards
i.e. stdout shows the critical stuff, go to the file for low level details

I tried something like this:
```  
    logger = get_logger(current_module())
    set_level(logger, "warn")   # Try to set the level of the console
    add_handler(logger, DefaultHandler("mylogfile$(fileStartidx).log"), "file-logging")
    set_level(logger, "debug")  # Hopefully only set the level of the new file handler
```

Although as I kind of expected both now show from debug. 
Thus is there a way to call set_level only on a certain handler?
Or would I need to do something like:
Use set_level on warn, but create a custom version of the console handler that filters based on the level?
Or can I achieve this with parents set to different levels?

Thanks

**Comment by Rory-Finnegan** [comment]
It's possible, but I don't really like either solution. The default handlers don't filter based on log level, they simply take a `Record`,`format` it, and pass the resulting string to an `IO` type. I realize this is something folks may want to do, but I don't think handlers should need to know about that. I think adding support for applying `Filter`s to a `LogStream` is probably the better approach, but I haven't gotten around to implementing that. If this is a priority I can try to get something implemented in the next few weeks.

For now, there are 2 options:

1) The more local option is to set the STDOUT level of a parent logger (e.g., the root logger with `basic_config("warn")` and add the file handler to a child logger (ie: `get_logger(current_module())`) where you can set it with `set_level(logger, "debug")`.
2) The more global solution is to special case the `log` method for operating on the IOStream (STDOUT is `Base.TTY`) from a file, similar to the syslog example provided [here](https://invenia.github.io/Memento.jl/latest/man/handlers.html)

**Comment by Rory-Finnegan** [comment]
If you want to take a look I've added a slightly better solution in the "filters" branch. The summary is that you could add a filter to a handler with something like:
```julia
add_filter(handler, Filter((rec) -> rec[:levelnum] >= LEVELS["warn"]))
```
I'm still reluctant to couple the logger (and logging levels) to the handlers, but this seems like an okay middle ground.

**Comment by Rory-Finnegan** [comment]
I've merged the work from the filters branch mentioned above into master. If you find that solution doesn't satisfy your requirements please reopen this issue.

**Comment by Rory-Finnegan** [comment]
@lwabeke I forgot to mention that the master branch also includes a `set_level` method for handlers, to address your particular use case.
```julia
help?> set_level
search: set_level

  set_level(handler::DefaultHandler, level::AbstractString)

  Sets the minimum level required to emit the record from the handler.

  set_level(logger::Logger, level::AbstractString)

  Changes what level this logger should log at.
```

**Comment by lwabeke** [comment]
Thanks, I'll give it a try at some point. I have managed well with the parent child logger you suggested (atleast I think that was what I ended up using). I believe I managed to get the functionality I was hoping for.
At this stage, I'm focusing on other issues, so it might be a while before I can try this again.
