### ISSUE TITLE
Include both message and caught error

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/Memento.jl#126]
Currently I write something like this (or some other workaround)
```julia
try
    ...
catch err
    err isa ArgumentError || rethrow(err)
    warn(logger, "message...")
    error(logger, err)
end
```

But perhaps it should be possible to write this?
```julia
error(logger, "message...", err)
```

**Comment by rofinn** [comment]
I think the typical pattern for this is to wrap the exception in another exception

**Comment by nickrobinson251** [comment]
I am glad there is another way, but I do not know what that means, please can you give an example?

**Comment by rofinn** [comment]
```
try
    ...
catch err
    err isa ArgumentError || rethrow(err)
    error(logger, ErrorException("message ... " * sprint(io -> showerror(io, err)))
end
```

**Comment by rofinn** [comment]
If it is a common enough pattern then typically a new container exception type is defined (e.g.,` HTTP.IOError`, `CaptureException`).

**Comment by rofinn** [comment]
Unless I'm mistaken there isn't anything here that Memento needs to fix?

**Comment by nickrobinson251** [comment]
`error(logger::Logger, msg::AbstractString, e::Excpetion) = error(logger, ErrorException(msg * sprint(io -> showerror(io, e)))`?
