### ISSUE TITLE
Add docs Manual section for TestUtils

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/Memento.jl#129]
I find `Memento.TestUtils` very useful :) thanks!

And the public API for `Memento.TestUtils` is documented at https://invenia.github.io/Memento.jl/latest/api/public/#Memento.TestUtils-1

But... i have previosuly struggled to find this, and correctly using things like `@test_nolog` is still always a matter a trial-and-error for me.

I think it'd be useful to add a section on `TestUtils` to the docs Manual, with examples and to make this useful functionality more prominent

**Comment by rofinn** [comment]
Yeah, I intentionally didn't want to publicize the functionality too much when I wrote the `Memento.Test` module as I wasn't entirely happy with the behaviour. I feel like we're using it enough now that we should just document it properly and deprecate any changes we need to make going forward.

**Comment by nickrobinson251** [comment]
Did this get added?

**Comment by nickrobinson251** [comment]
Yes, to the faq in https://github.com/invenia/Memento.jl/pull/150
