### ISSUE TITLE
TZ Environment

### ISSUE THREAD

**Issue by natgeo-wong** [invenia/Memento.jl#136]
Hello!  I've encoutered a TZ environment that cannot be handled by Memento.

Unhandled TZ environment variable format: "EST5EDT,M3.2.0,M11.1.0"

Does anyone have any workarounds for this?  I'm using a Linux server cluster here, so I'm not sure if i would have any permissions to change timezone formatting, etc.

**Comment by iamed2** [comment]
This is up to TimeZones to fix, in the issue you opened there. 

You can always edit the TZ environment variable for just your Julia session, using `ENV` or `withenv`.
