### ISSUE TITLE
Bump TimeZones to 0.10.3

### ISSUE THREAD

**Issue by colinxs** [invenia/Memento.jl#139]
TimeZones < 0.10.3 is broken on Julia 1.3: https://github.com/JuliaTime/TimeZones.jl/issues/238.

Consider bumping compat?

**Comment by rofinn** [comment]
Why would it be necessary for Memento to do that? AFAICT, nothing about the TimeZones API has changed to warrant that restriction. We aren't upperbounding it TimeZones in any way, so a simple `pkg> up` should suffice.
