### ISSUE TITLE
Release version 1.0?

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/Memento.jl#144]
Are there any issues / redesigns blocking us from releasing Memento v1.0?

**Comment by rofinn** [comment]
None active, but if you scan through the issues there are multiple features that need to be fixed, added or documented prior to making a 1.0 release. At this point I don't know when/if those will be completed as I don't think anyone is actively working on (or maintaining) this package anymore.

**Comment by nickrobinson251** [comment]
Shall we label them with a `v1` milestone, so we know when we're good to release v1?

**Comment by iamed2** [comment]
> there are multiple features that need to be fixed, added or documented prior to making a 1.0 release

The only reason for such issues to block 1.0 is if they are breaking changes, but if no one's going to be working on them, then avoiding 1.0 just causes headaches when what would be minor version bumps are released as 0.x releases.

**Comment by rofinn** [comment]
Made a milestone for the easy things to address. I've left the more severely breaking changes for a different major release as I'm no longer actively developing this package.

**Comment by nickrobinson251** [comment]
Lots of good stuff gone in over the last couple weeks :) How we looking for a v1.0 release?
