### ISSUE TITLE
Zero overhead logging macros (as with Logging.jl)

### ISSUE THREAD

**Issue by stustd** [invenia/Memento.jl#15]
As with Logging.jl, including this code as macros.jl file provides (zero overhead) logging macros when log level is below threshold.  
```
export @debug, @info, @notice, @warn, @error, @critical, @alert, @emergency

for (mac,fn,lvl) in ((:debug,     :(Memento.debug),     Memento._log_levels["debug"]),
                     (:info,      :(Memento.info),      Memento._log_levels["info"]),
                     (:notice,    :(Memento.notice),    Memento._log_levels["notice"]),
                     (:warn,      :(Memento.warn),      Memento._log_levels["warn"]),
                     (:error,     :(Memento.error),     Memento._log_levels["error"]),
                     (:critical,  :(Memento.critical),  Memento._log_levels["critical"]),
                     (:alert,     :(Memento.alert),     Memento._log_levels["alert"]),
                     (:emergency, :(Memento.emergency), Memento._log_levels["emergency"])
                     )

    @eval macro $mac(msg...)

        logger = eval(msg[1])

        # println("$($lvl), $(Memento._log_levels[logger.level])")

        if Memento._log_levels[logger.level] > $lvl
            :nothing
        else
            Expr(:call, $fn, msg...)
        end
    end

end
```

**Comment by Rory-Finnegan** [comment]
This is something I've considered adding in past, however there are a few issues:

1. As stated in the Logging.jl README
> ... changing the log level later in the code will not have any affect on previously evaluated functions, though it does affect future evaluation

This is seems like it could lead to bugs that are difficult to debug.

2. Similarly, we're intending packages to simply use `get_logger(current_module()` and `log` (`debug`, `info`, etc), while leaving the configuration to the application code. If we allow some libraries to use macros then applications will need to be configured in a macro, and that macro will likely need to be run prior to including other library content (just to be safe).

While these issues aren't deal breakers they are rather ugly. Currently, my priorities are:

1. Make it flexible
2. Make it correct (ie:  well tested & documented)
3. Make it easy to use
4. Make it fast

**Comment by stustd** [comment]
Regarding:

1) That's true. However the macros are useful in debugging during actual code development, e.g. monitoring the behavior of complex algorithms. Once results are as intended (perhaps for the moment...) all debug statements can be voided with a single switch without removing all the @debug statements (just in case they're needed when other design issues pop up at a later stage - then it's back to the design again).

2)  You're right, application developers should not use the macros; the macros are only useful during the library design stage.

Thus, IMO adding the macros to you library would expand its functionality so long as their proper use (i.e. development rather than productivity) is understood.

**Comment by stustd** [comment]
Regarding:

That's true. However the macros are useful in debugging during actual code development, e.g. monitoring the behavior of complex algorithms. Once results are as intended (perhaps for the moment...) all debug statements can be voided with a single switch without removing all the @debug statements (just in case they're needed when other design issues pop up at a later stage - then it's back to the design again).

You're right, application developers should not use the macros; the macros are only useful during the library design stage.

Thus, IMO adding the macros to you library would expand its functionality so long as their proper use (i.e. development rather than productivity) is understood.

**Comment by Rory-Finnegan** [comment]
Okay, that seems like a reasonable compromise.

**Comment by Rory-Finnegan** [comment]
@stustd I have a couple more questions.

1. What existing features of Memento.jl should be available inside these macros? I imagine folks just want to be dumping there debugging information to standard out rather than using custom IO types, Handlers, Formatters, Records, etc? Similarly, I don't think the hierarchical logging functionality really fits in with this.
2. Does that still even qualify as logging or does is the data uniquely different, and should it be treated as such.

An alternative solution may be to have a separate package for handling this kind of debugging information. Perhaps it simply exposes an `@verbose` macro.

**Comment by stustd** [comment]
Regarding:

1) When I use(d) the Logging.jl macros I just capitalize on the structured formatting functionality, and indeed, not much more. However, I can imagine that sometimes file output may come in handy, especially for nasty/verbose debugging problems. I wouldn't bother much about Handlers, Formatters and Records.

2) In my experience I haven't encountered debugging data that didn't fall within the range of the logger's capabilities, so the macros suited my needs.

You're alternative suggestion is perfectly possible, and only a @debug macro (instead of @verbose) would suffice.

**Comment by Rory-Finnegan** [comment]
Alright, [here](https://github.com/invenia/Trace.jl) is a prototype package. I'm not a fan of using `@debug` as I don't like the overlap with the `debug` method.

The general usage is:
```julia
julia> using Trace

julia> @time @trace "Foobar"
  0.000001 seconds (4 allocations: 160 bytes)

julia> @Trace.config()
Logger(Trace)

julia> @time @trace "Foobar"
[trace | collect_to!@array.jl:340]: Foobar
  0.002314 seconds (545 allocations: 33.016 KB)
```

**Comment by rofinn** [comment]
NOTE: You can now use Memento to format the base Logging records by calling `Memento.substitute!`. The base `@debug` macro is disabled by default and you can control that via environment variables completely independent of Memento.
