### ISSUE TITLE
Allow customising date format

### ISSUE THREAD

**Issue by gasagna** [invenia/Memento.jl#175]
Hi, 

thanks for the great package.

I need to log events with sub-second accuracy, but it looks like the date format is hard-coded by the constant `DATE_FMT_STRING = "yyyy-mm-dd HH:MM:SS"` in `src/formatters.jl`. 

It would be nice if the date format string was fully customisable, for greater flexibility.

**Comment by tpgillam** [comment]
Hi @gasagna , this should now be doable with the new argument to `DefaultFormatter` in v1.2.0. For example:

```DefaultFormatter("{date}"; date_fmt_string="yyyy-mm-dd HH:MM:SS.s")```

will print just the datetime, including milliseconds.
