### ISSUE TITLE
Use sockets for syslog handler

### ISSUE THREAD

**Issue by omus** [invenia/Memento.jl#32]
Currently the Syslog handler [uses the command line tool `logger`](https://github.com/invenia/Memento.jl/blob/e13f768c80531e0937e6dad31a18842f5c886069/src/io.jl#L155) to be able to write logs. Memento should instead send logs over UDP/TCP which would allow the handler to write logs directly to remote syslog servers (for example see [Python's syslog handler](https://docs.python.org/2/library/logging.handlers.html#logging.handlers.SysLogHandler)). Additionally, some systems may not have this tool installed (aka. Docker containers) and using sockets would remove the `logger` requirement.

**Comment by rofinn** [comment]
1) Do we have a preference for UDP or TCP to start? Historically, syslog has used UDP on port 514 by default...
2) Do we want to support TLS/DTLS? Looks like python's syslog handler doesn't, but we might be able to use MbedTLS.jl.

**Comment by omus** [comment]
I was thinking UDP to start with. I'll check on Monday what the preferred settings are.

**Comment by rofinn** [comment]
I'll be moving the syslog handler out of Memento.jl into [SystemLog.jl](https://github.com/invenia/SystemLog.jl). The first pass has been pushed to the master which includes:

1. Logging locally with the libc interface (unix only)
2. Logging remotely with UDP or TCP (not supporting TLS or DTLS).
3. Uses the minimal protocol requirements (e.g., `<$prio>$msg\0`), but it sounds like a custom Memento record format may be needed some some syslog servers. 

We'll probably still have some syslog specific code in Memento, but we should be able to avoid having SystemLog as a dependency by using Requires.jl
