### ISSUE TITLE
Default level to info

### ISSUE THREAD

**Issue by rofinn** [invenia/Memento.jl#70]
There has been some [discussion](https://github.com/invenia/Memento.jl/issues/69#issuecomment-387818133)  around changing the default logging level to `"info"` to better align with base. I usually don't want to see `"info"` messages in production code, but I can always do `Memento.config("warn")` if necessary. Please up or down vote this issue to express your preference (upvote if you'd like the default to be `"info"`).

**Comment by omus** [comment]
I would be ok with it. Maybe info should be the default when running interactive otherwise stick to warn?

**Comment by omus** [comment]
I can agree with having the behaviour be consistent is important. What about mentioning in the documentation to have `Memento.config("info")` as part of the `~/.juliarc.jl` file?

**Comment by rofinn** [comment]
Running `Memento.config("info")` isn't the same thing. We'd want to add a recursive flag for that to work... which we might want to do regardless.

**Comment by rofinn** [comment]
I'll try testing a few permutations with several packages to see what works best and report back. If we can manage most use cases with just a single function call then I'll be happy.
